### ISSUE TITLE
Rewrite formatMessage to return parsed version of content

### ISSUE THREAD

**Issue by tatupesonen** [tatupesonen/formatbot#24]
Currently, `formatMessage` returns a string which locks down on possibilities to perform other operations on the returned data.
`formatMessage` should only extract the information it can from the content, without performing operations such as running formatters on it or autodetecting language.

Example of the preferred new return type:
```ts
type BLOCK_MODE = "text" | "code";
type MesageBlock = {
  type: BLOCK_MODE;
  content: string;
  languageKey?: keyof typeof languageMappings; // eg. "js"
  order: number;
};
const formatResult: MessageBlock[] = await formatMessage(content);
```

**Comment by BenjammingKirby** [comment]
so code blocks for unsupported languages count as text blocks too, right?

**Comment by tatupesonen** [comment]
@BenjammingKirby 

> so code blocks for unsupported languages count as text blocks too, right?

No, the triple backticks inside them should be detected as a code block. (so have `type: "code"`.
As long as we know that the block contains code, we can then look at the `languageKey` of that block and if it has a compatible formatter we run that on the code. If it's a codeblock without a `languageKey` we still mark it as containing code, because we can possibly autodetect it using guesslang.

**Comment by tatupesonen** [comment]
WIP implementation with it only returning code blocks currently:
1559906d7197717fbf9e4c97e4e1e6ff170463af
fdc878fb1f362088cad45dd1024abbd119df397e
