### ISSUE TITLE
Conditional command arguments

### ISSUE THREAD

**Issue by daniellwdb** [tatupesonen/formatbot#42]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [x] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
[here](https://github.com/tatupesonen/formatbot/blob/dev/src/lib/interfaces/ICommand.ts#L15) it seems like you defined `args` as a possible array of strings, I assume this is determined based on the command type, while you aren't using args anywhere, I think it could still be nice to conditionally accept the right arguments, what do you think?
```typescript
export interface ICommand<
  T extends typeof COMMAND_TYPE[keyof typeof COMMAND_TYPE]
> {
  execute(...args: Mapped[T], container: Container): void;
}

interface Mapped {
  [COMMAND_TYPE.CHANNEL]: [interaction: CommandInteraction];
  [COMMAND_TYPE.SLASH]: [interaction: ContextMenuInteraction];
  [COMMAND_TYPE.LEGACY]: [message: Message, args: string[]];
}
```

**Comment by tatupesonen** [comment]
Good idea! I will implement this fix for the next release. Thanks for the feedback :)

**Comment by daniellwdb** [comment]
Just made one, hope you like it
