### ISSUE TITLE
FormatBot status command getting triggered on message replies

### ISSUE THREAD

**Issue by jdeurt** [tatupesonen/formatbot#71]
- **I'm submitting a ...**
[x] bug report
[x] feature request
[  ] question about the decisions made in the repository
[  ] question about how to use this project

- **Summary**
Format bot will respond with a big info embed on replies that ping the bot. This behavior is probably not intended.
Also, consider removing extraneous information from the embed such as library versions as those take up unnecessary space in chat.

- **Other information** (eg. screenshots of the bot failing formatting or crashing / not responding)
<img width="593" alt="Screenshot 2023-03-11 at 10 42 57 PM" src="https://user-images.githubusercontent.com/27937441/224524841-b7e30029-779b-40fb-ba20-ce45397c2de6.png">

**Comment by jdeurt** [comment]
https://github.com/tatupesonen/formatbot/blob/2b6c3a07badfa015657766092cd3e06f9cc63fe1/src/lib/bot.ts#L48

Looks like this line is causing the issue. There should be a way to check whether or not the ping is direct more safely.

**Comment by jdeurt** [comment]
https://github.com/tatupesonen/formatbot/pull/72 fixes this issue.

**Comment by tatupesonen** [comment]
Thanks for the PR. Yeah the current logic is to check if a message only contains a FormatBot ping and in that case, send the embed. However I think we can go with your suggested changes, so I'll take a look at your PR.
